markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "xinbinhao"
markdown: rdiscount

author: "xinbinhao"
atom-baseurl: "http://xinbinhao.github.com"
disqus: "gopherwood"

navigations:
  - title: home
    class: fa fa-home
    href: /
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html

